#pragma once
#include <stdint.h>
#include "scene.h"

extern const scene_t SCENE_01_BOOT_TITLE;
extern const scene_t SCENE_02_COPPER_SCROLLER;
extern const scene_t SCENE_03_STARFIELD;
extern const scene_t SCENE_04_CUBE;
extern const scene_t SCENE_05_PLASMA;
extern const scene_t SCENE_06_METABALLS;
extern const scene_t SCENE_07_ROTOZOOMER;
extern const scene_t SCENE_08_SILHOUETTE;
extern const scene_t SCENE_09_VOXEL;
extern const scene_t SCENE_10_TUNNEL;
extern const scene_t SCENE_11_SYNTHWAVE;
extern const scene_t SCENE_12_CREDITS;

/* Silhouette frame data baked into flash rodata. Generated by
 * tools/gen_silhouette_placeholder.py into components/scenes/scene_08_frames.c. */
extern const uint8_t SCENE_08_FRAMES[60][750];
extern const int     SCENE_08_FRAME_COUNT;
extern const int     SCENE_08_FRAME_BYTES;
