#pragma once
#include <stdint.h>
#include "scene.h"
extern const scene_t SCENE_01_BOOT_TITLE;
extern const scene_t SCENE_02_COPPER_SCROLLER;
extern const scene_t SCENE_03_STARFIELD;
extern const scene_t SCENE_04_CUBE;
extern const scene_t SCENE_05_PLASMA;
extern const scene_t SCENE_08_SILHOUETTE;

/* Silhouette frame data baked into flash rodata. Generated by
 * tools/gen_silhouette_placeholder.py into components/scenes/scene_08_frames.c.
 * Phase 1 dropped the SD-card path entirely; the frames are always available
 * to Scene 8 via these symbols, no boot-time loading required. */
extern const uint8_t SCENE_08_FRAMES[60][750];
extern const int     SCENE_08_FRAME_COUNT;
extern const int     SCENE_08_FRAME_BYTES;
