#!/usr/bin/env python3
"""Generate 60 placeholder silhouette frames as 1-bit packed bitmaps.

Outputs:
  1. sdcard/silhouettes/frame_NNN.bin (60x100, 750 bytes each) — kept
     as a useful artefact for future user-supplied frame workflows.
  2. components/scenes/scene_08_frames.c — a const C array baked into
     flash rodata. This is what the ESP32 firmware actually reads at
     runtime in Phase 1 (SD path was dropped: see commit dropping SD).

The 'silhouette' is just a bouncing oval — proves the pipeline works
end-to-end. Real rotoscoped frames replace these in Phase 3."""

import math
import os

W, H, FRAMES = 60, 100, 60
FRAME_BYTES = (W * H + 7) // 8   # 750
OUT_DIR = "sdcard/silhouettes"
C_OUT = "components/scenes/scene_08_frames.c"

os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(os.path.dirname(C_OUT), exist_ok=True)

frames = []
for f in range(FRAMES):
    bits = bytearray(FRAME_BYTES)
    cy = int(50 + 30 * math.sin(2 * math.pi * f / FRAMES))
    cx = 30
    for y in range(H):
        for x in range(W):
            inside = ((x - cx) / 18.0) ** 2 + ((y - cy) / 28.0) ** 2 <= 1.0
            if inside:
                byte = (y * W + x) // 8
                bit = (y * W + x) % 8
                bits[byte] |= (1 << bit)
    path = os.path.join(OUT_DIR, f"frame_{f:03d}.bin")
    with open(path, "wb") as out:
        out.write(bits)
    frames.append(bytes(bits))
print(f"wrote {FRAMES} frames to {OUT_DIR}")

# --- Emit C array ---------------------------------------------------------
def fmt_frame(idx, data):
    lines = [f"    {{ /* frame {idx} */"]
    for chunk_start in range(0, len(data), 16):
        chunk = data[chunk_start:chunk_start + 16]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        suffix = "," if chunk_start + 16 < len(data) else ""
        lines.append(f"        {hex_bytes}{suffix}")
    lines.append("    }")
    return "\n".join(lines)

with open(C_OUT, "w") as out:
    out.write("/* Auto-generated by tools/gen_silhouette_placeholder.py -- DO NOT EDIT.\n")
    out.write(f" * {FRAMES} frames x {FRAME_BYTES} bytes ({W}x{H} 1-bit packed).\n")
    out.write(" * Lives in flash rodata; consumed by components/scenes/scene_08_silhouette.c.\n")
    out.write(" */\n")
    out.write("#include <stdint.h>\n\n")
    out.write(f"const uint8_t SCENE_08_FRAMES[{FRAMES}][{FRAME_BYTES}] = {{\n")
    out.write(",\n".join(fmt_frame(i, frames[i]) for i in range(FRAMES)))
    out.write("\n};\n\n")
    out.write(f"const int SCENE_08_FRAME_COUNT = {FRAMES};\n")
    out.write(f"const int SCENE_08_FRAME_BYTES = {FRAME_BYTES};\n")

print(f"wrote {C_OUT} ({os.path.getsize(C_OUT)} bytes)")
